language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update --prefer-source

script:
  - php vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

addons:
    code_climate:
        repo_token: 816794d0b77c426044505c96d157e8e0cdc13eb94e28323ee80e3d09eeb761d1